"""Catalog coverage audit for part D (Hollywood enrichment): measured numbers only.

Writes artifacts/metrics/catalog_audit.json and docs/catalog-audit.md.
"""
from collections import Counter

import pandas as pd

from pipeline.common import ARTIFACTS, ROOT, write_json
from pipeline.selection import hollywood_rule


def _missing_reason(row, h: dict, window_end) -> str:
    if row["reasons"]:
        return "failed gate: " + ", ".join(row["reasons"])
    if row["status"] != "Released" or not row["release_date"] or pd.to_datetime(row["release_date"]).date() > window_end:
        return "not released yet"
    if not hollywood_rule(pd.DataFrame([row]), h).iloc[0]:
        return "below the part-D vote rule"
    return "not selected (unexpected)"


def write_catalog_audit(gated: pd.DataFrame, movies: pd.DataFrame, h: dict, window_end) -> dict:
    in_catalog = set(movies["tmdb_id"])
    part_of = dict(zip(movies["tmdb_id"], movies["catalog_part"]))

    us = (gated[(gated["part"] == "D") & gated["us_production"].fillna(False).astype(bool)]
          .drop_duplicates("tmdb_id").sort_values("tmdb_vote_count", ascending=False).reset_index(drop=True))
    us["catalog_part"] = us["tmdb_id"].map(part_of)
    qualifying = us[hollywood_rule(us, h)]
    failed = qualifying[qualifying["catalog_part"].isna() & ~qualifying["passed"]]

    def coverage(n: int) -> dict:
        top = us.head(n)
        got = top["tmdb_id"].isin(in_catalog)
        return {"films": int(len(top)), "in_catalog": int(got.sum()), "pct": round(100 * got.mean(), 1),
                "by_part": top["catalog_part"].value_counts().to_dict()}

    top1000 = us.head(1000)
    missing = [
        {"rank": int(i + 1), "tmdb_id": int(r["tmdb_id"]), "title": r["title"],
         "year": None if pd.isna(r["year"]) else int(r["year"]),
         "votes": int(r["tmdb_vote_count"]), "reason": _missing_reason(r, h, window_end)}
        for i, r in top1000.iterrows() if r["tmdb_id"] not in in_catalog
    ]
    d = movies[movies["catalog_part"] == "D"]
    audit = {
        "rule": h,
        "us_candidates_found": int(len(us)),
        "us_candidates_meeting_rule": int(len(qualifying)),
        "already_in_A": int((us["catalog_part"] == "A").sum()),
        "already_in_B_or_C": int(us["catalog_part"].isin(["B", "C"]).sum()),
        "added_as_D": int(len(d)),
        "failed_gate": int(len(failed)),
        "failed_gate_by_reason": dict(Counter(x for rs in failed["reasons"] for x in rs).most_common()),
        "coverage_top_500_us": coverage(500),
        "coverage_top_1000_us": coverage(1000),
        "top_1000_missing": missing,
        "catalog_by_part": movies["catalog_part"].value_counts().sort_index().to_dict(),
        "catalog_by_language": movies["original_language"].value_counts().to_dict(),
        "catalog_total": int(len(movies)),
        "added_by_relaxed_gate": (movies.loc[movies["relaxed_gate"], "catalog_part"].value_counts().sort_index().to_dict()
                                  if "relaxed_gate" in movies else {}),
    }
    write_json(ARTIFACTS / "metrics" / "catalog_audit.json", audit)

    lines = [
        "# Catalog audit", "",
        "Generated by pipeline step 5 from cached TMDB data. All numbers are measured.", "",
        "## Part D rule (pipeline/catalog_config.yaml)", "",
        f"US production (co-productions count), not already in A/B/C, metadata gate passed, released, and "
        f"votes >= {h['min_vote_count']}, or votes >= {h['classic_min_vote_count']} and released before "
        f"{h['classic_before_year']}, or votes >= {h['collection_min_vote_count']} and part of a TMDB collection.", "",
        "## Hollywood coverage", "",
        "| Measure | Films |", "|---|---|",
        f"| US films in the TMDB pool (>= {h['pool_min_vote_count']} votes) | {audit['us_candidates_found']:,} |",
        f"| ...meeting the part-D rule | {audit['us_candidates_meeting_rule']:,} |",
        f"| Already in part A | {audit['already_in_A']:,} |",
        f"| Already in part B or C | {audit['already_in_B_or_C']:,} |",
        f"| Added as part D | {audit['added_as_D']:,} |",
        f"| Failed the metadata gate | {audit['failed_gate']:,} |", "",
        f"Gate failures by reason: {audit['failed_gate_by_reason'] or 'none'}", "",
        f"Top 500 US films by TMDB votes in the catalog: **{audit['coverage_top_500_us']['in_catalog']} of 500 "
        f"({audit['coverage_top_500_us']['pct']}%)**", "",
        f"Top 1000 US films by TMDB votes in the catalog: **{audit['coverage_top_1000_us']['in_catalog']} of 1000 "
        f"({audit['coverage_top_1000_us']['pct']}%)**", "",
        "## Top-1000 US films still missing", "",
        "| Rank | Title | Year | Votes | Reason |", "|---|---|---|---|---|",
    ]
    lines += [f"| {m['rank']} | {m['title']} | {m['year'] or ''} | {m['votes']:,} | {m['reason']} |" for m in missing] or ["| - | none | | | |"]
    lines += ["", "## Catalog composition", "", "| Part | Films |", "|---|---|"]
    lines += [f"| {k} | {v:,} |" for k, v in audit["catalog_by_part"].items()]
    lines += [f"| **Total** | **{audit['catalog_total']:,}** |", ""]
    if audit["added_by_relaxed_gate"]:
        added = audit["added_by_relaxed_gate"]
        lines += [f"Of these, {sum(added.values()):,} films ({', '.join(f'{k} {v:,}' for k, v in added.items())}) pass only the "
                  "relaxed metadata gate (overview >= 10 words, >= 1 cast member). They were added on top of the cut "
                  "made with the original gate (15 words, 3 cast), with its thresholds, and are outside the "
                  "evaluation backbone.", ""]
    lines += ["| Language | Films |", "|---|---|"]
    lines += [f"| {k} | {v:,} |" for k, v in audit["catalog_by_language"].items() if v >= 10]
    lines += ["", "Languages with fewer than 10 films are listed in artifacts/metrics/catalog_audit.json.", ""]
    (ROOT / "docs" / "catalog-audit.md").write_text("\n".join(lines), encoding="utf-8")
    return audit